aoc_select_year_idx = 7

aoc_select_day_idx = 1

open_task_command = [
    # for nvid (new window):
    # '/home/yosuanicolaus/app/bin/nvid',
    # '--fork',
    # '$FILE',

    # for nvim:
    # '/usr/bin/nvim',
    # '--server',
    # 'localhost:3708',
    # '--remote-send',
    # '"<ESC><ESC>:n $FILE<CR>:call cursor($LINE, $COLUMN)<CR>"',
    
    # for vscode:
    # '/usr/bin/code-insiders',
    # '-r',
    # '--goto',
    # '$FILE:$LINE:$COLUMN',

    # for RustRover:
    "/home/yosuanicolaus/.local/share/JetBrains/Toolbox/apps/rustrover/bin/rustrover",
    "--line",
    "$LINE",
    "--column",
    "$COLUMN",
    "$FILE",
]
